#pragma once

#define FXanimation L"shader\\animation.fx"
#define FXAtlasPick L"shader\\AtlasPick.fx"
#define FXdebug L"shader\\debug.fx"
#define FXfunc L"shader\\func.fx"
#define FXMapGeneratorBlock L"shader\\MapGeneratorBlock.fx"
#define FXparticle L"shader\\particle.fx"
#define FXparticle_update L"shader\\particle_update.fx"
#define FXpostprocess L"shader\\postprocess.fx"
#define FXsetcolor L"shader\\setcolor.fx"
#define FXstd2d L"shader\\std2d.fx"
#define FXstruct L"shader\\struct.fx"
#define FXtile L"shader\\tile.fx"
#define FXtilemap L"shader\\tilemap.fx"
#define FXvalue L"shader\\value.fx"
