#pragma once

#define StrPlayerName L"Player"
#define StrMonsterHitColliderName L"HitCollider"
#define StrMonsterDetectColliderName L"DetectCollider"

#define TitleCursor L"prefab\\TitleCursor.pref"
#define TitleSelect01 L"prefab\\TitleSelect01.pref"
#define TitleSelect02 L"prefab\\TitleSelect02.pref"
#define TitleSelect03 L"prefab\\TitleSelect03.pref"
#define TitleSelectDoor1 L"prefab\\TitleSelectDoor1.pref"
#define TitleSelectDoor2 L"prefab\\TitleSelectDoor2.pref"
#define TitleSelectFloor L"prefab\\TitleSelectFloor.pref"
#define TitleFire L"prefab\\TitleFire.pref"
#define TitleAnyKey L"prefab\\TitleAnyKey.pref"
#define TitleBackgroundPrefKey L"prefab\\TitleBackground.pref"
#define TitleGirlPrefKey L"prefab\\TitleGirl.pref"
#define TilePrefKey L"prefab\\Tile.pref"
#define PlayerPrefKey L"prefab\\Player.pref"
#define WhipPrefKey L"prefab\\Whip.pref"
#define BombPrefKey L"prefab\\Bomb.pref"
#define RopePrefKey L"prefab\\Rope.pref"
#define OutlineWallKey L"prefab\\OutlineWall.pref"
#define SnakePrefKey L"prefab\\Snake.pref"
#define RockPrefKey L"prefab\\Rock.pref"
#define HUDBombPrefKey L"prefab\\HUDBomb.pref"
#define HUDHeartPrefKey L"prefab\\HUDHeart.pref"
#define HUDRopePrefKey L"prefab\\HUDRope.pref"
#define HUDScorePrefKey L"prefab\\HUDScore.pref"
#define HUDTimePrefKey L"prefab\\HUDTime.pref"
#define HUDStagePrefKey L"prefab\\HUDStage.pref"
#define ParticleCloudPrefKey L"prefab\\ParticleCloud.pref"
#define ParticleBloodPrefKey L"prefab\\ParticleBlood.pref"
#define ParticleStarPrefKey L"prefab\\ParticleStar.pref"
#define ParticleSoilPrefKey L"prefab\\ParticleSoil.pref"
#define ParticleTreePrefKey L"prefab\\ParticleTree.pref"
#define ParticleFirePrefKey L"prefab\\ParticleFire.pref"

#define BBOwnerKey L"Owner"
#define BBJumpDelay L"JumpDelay"

#define ChunkPath L"stage\\DwellingChunk.ck"

#define CameraColliderWallName L"CameraWallCollider"
#define CameraColliderPlatformName L"CameraPlatformCollider"

#define OutlineAtlasPath L"texture\\tilemap\\border_main.png"

#define OutlineWallName L"OutlineWall"

#define AnimPlayerIdle L"anim\\PlayerIdle.anim"
#define AnimPlayerHandleIdle L"anim\\PlayerHandleIdle.anim"
#define AnimPlayerJumpUp L"anim\\PlayerJumpUp.anim"
#define AnimPlayerJumpFall L"anim\\PlayerJumpFall.anim"
#define AnimPlayerWalk L"anim\\PlayerWalk.anim"
#define AnimPlayerDown L"anim\\PlayerDown.anim"
#define AnimPlayerDownIdle L"anim\\PlayerDownIdle.anim"
#define AnimPlayerUp L"anim\\PlayerUp.anim"
#define AnimPlayerCrawl L"anim\\PlayerCrawl.anim"
#define AnimPlayerThrow L"anim\\PlayerThrow.anim"
#define AnimPlayerAttack L"anim\\PlayerAttack.anim"
#define AnimPlayerLadder L"anim\\PlayerLadder.anim"

#define AnimWhip L"anim\\Whip.anim"
#define AnimBombBlack L"anim\\BombBlack.anim"
#define AnimBombRed L"anim\\BombRed.anim"
#define AnimBombYellow L"anim\\BombYellow.anim"
#define AnimBombExplosion L"anim\\BombExplosion.anim"

#define AnimSnakeIdle L"anim\\SnakeIdle.anim"
#define AnimSnakeWalk L"anim\\SnakeWalk.anim"
#define AnimSnakeAttack L"anim\\SnakeAttack.anim"
#define AnimRock L"anim\\Rock.anim"

#define AnimHUDHeart L"anim\\HUDHeart.anim"
#define AnimHUDBomb L"anim\\HUDBomb.anim"
#define AnimHUDRope L"anim\\HUDRope.anim"
#define AnimHUDScore L"anim\\HUDScore.anim"
#define AnimHUDTime L"anim\\HUDTime.anim"
#define AnimHUDStage L"anim\\HUDStage.anim"

#define AnimTitleAnyKey L"anim\\TitleAnyKey.anim"
#define AnimTitleBackground L"anim\\TitleBackground.anim"
#define AnimTitleGirl L"anim\\TitleGirl.anim"
#define AnimTitleCursor L"anim\\TitleCursor.anim"
#define AnimTitleSelect01 L"anim\\TitleSelect01.anim"
#define AnimTitleSelect02 L"anim\\TitleSelect02.anim"
#define AnimTitleSelect03 L"anim\\TitleSelect03.anim"
#define AnimTitleSelectDoor1 L"anim\\TitleSelectDoor1.anim"
#define AnimTitleSelectDoor2 L"anim\\TitleSelectDoor2.anim"
#define AnimTitleSelectFloor L"anim\\TitleSelectFloor.anim"

#define StatePlayerIdle L"CPlayerIdleState"
#define StatePlayerDown L"CPlayerDownState"
#define StatePlayerJumpUp L"CPlayerJumpUpState"
#define StatePlayerFallDown L"CPlayerFallDownState"
#define StatePlayerWalk L"CPlayerWalkState"
#define StatePlayerThrow L"CPlayerThrowState"
#define StatePlayerAttack L"CPlayerAttackState"
#define StatePlayerLadder L"CPlayerLadderState"

#define TexParticleRubbleAtlas L"texture\\atlas\\fx_rubble.png"
#define TexParticleSmallAtlas L"texture\\atlas\\fx_small.png"

#define StateEndSymbol "STATE_END"

