#pragma once

#define StrPlayerName L"Player"
#define StrMonsterHitColliderName L"HitCollider"
#define StrMonsterDetectColliderName L"DetectCollider"

#define PauseMenuCursorPrefKey L"prefab\\PauseCursor.pref"
#define PauseMenuBoardPrefKey L"prefab\\PauseMenuBoard.pref"
#define PauseHeaderPrefKey L"prefab\\PauseHeader.pref"
#define PauseRockPrefKey L"prefab\\PauseRock.pref"
#define TitleCursor L"prefab\\TitleCursor.pref"
#define TitleSelect01 L"prefab\\TitleSelect01.pref"
#define TitleSelect02 L"prefab\\TitleSelect02.pref"
#define TitleSelect03 L"prefab\\TitleSelect03.pref"
#define TitleSelectDoor1 L"prefab\\TitleSelectDoor1.pref"
#define TitleSelectDoor2 L"prefab\\TitleSelectDoor2.pref"
#define TitleSelectFloor L"prefab\\TitleSelectFloor.pref"
#define TitleFire L"prefab\\TitleFire.pref"
#define TitleAnyKey L"prefab\\TitleAnyKey.pref"
#define TitleBackgroundPrefKey L"prefab\\TitleBackground.pref"
#define TitleGirlPrefKey L"prefab\\TitleGirl.pref"
#define TilePrefKey L"prefab\\Tile.pref"
#define PlayerPrefKey L"prefab\\Player.pref"
#define WhipPrefKey L"prefab\\Whip.pref"
#define BombPrefKey L"prefab\\Bomb.pref"
#define RopePrefKey L"prefab\\Rope.pref"
#define OutlineWallKey L"prefab\\OutlineWall.pref"
#define SnakePrefKey L"prefab\\Snake.pref"
#define RockPrefKey L"prefab\\Rock.pref"
#define HUDBombPrefKey L"prefab\\HUDBomb.pref"
#define HUDHeartPrefKey L"prefab\\HUDHeart.pref"
#define HUDRopePrefKey L"prefab\\HUDRope.pref"
#define HUDScorePrefKey L"prefab\\HUDScore.pref"
#define HUDTimePrefKey L"prefab\\HUDTime.pref"
#define HUDStagePrefKey L"prefab\\HUDStage.pref"
#define ParticleCloudPrefKey L"prefab\\ParticleCloud.pref"
#define ParticleBloodPrefKey L"prefab\\ParticleBlood.pref"
#define ParticleStarPrefKey L"prefab\\ParticleStar.pref"
#define ParticleSoilPrefKey L"prefab\\ParticleSoil.pref"
#define ParticleTreePrefKey L"prefab\\ParticleTree.pref"
#define ParticleFirePrefKey L"prefab\\ParticleFire.pref"
#define ButtonIconPrefKey L"prefab\\ButtonIcon.pref"

#define TileUp1PrefKey L"prefab\\TileUp1.pref"
#define TileSideRight1PrefKey L"prefab\\TileSideRight1.pref"
#define TileBottom1PrefKey L"prefab\\TileDown1.pref"

////////////////////////////////////////////////////////////////
#define BBOwnerKey L"Owner"
#define BBJumpDelay L"JumpDelay"

#define ChunkPath L"stage\\DwellingChunk.ck"

#define CameraColliderWallName L"CameraWallCollider"
#define CameraColliderPlatformName L"CameraPlatformCollider"

#define OutlineAtlasPath L"texture\\tilemap\\border_main.png"

#define OutlineWallName L"OutlineWall"

/////////////////////////////////////////////////
#define AnimPlayerIdle L"anim\\PlayerIdle.anim"
#define AnimPlayerHandleIdle L"anim\\PlayerHandleIdle.anim"
#define AnimPlayerJumpUp L"anim\\PlayerJumpUp.anim"
#define AnimPlayerJumpFall L"anim\\PlayerJumpFall.anim"
#define AnimPlayerWalk L"anim\\PlayerWalk.anim"
#define AnimPlayerDown L"anim\\PlayerDown.anim"
#define AnimPlayerDownIdle L"anim\\PlayerDownIdle.anim"
#define AnimPlayerUp L"anim\\PlayerUp.anim"
#define AnimPlayerCrawl L"anim\\PlayerCrawl.anim"
#define AnimPlayerThrow L"anim\\PlayerThrow.anim"
#define AnimPlayerAttack L"anim\\PlayerAttack.anim"
#define AnimPlayerLadder L"anim\\PlayerLadder.anim"
#define AnimPlayerExit L"anim\\PlayerExit.anim"

#define AnimWhip L"anim\\Whip.anim"
#define AnimBombBlack L"anim\\BombBlack.anim"
#define AnimBombRed L"anim\\BombRed.anim"
#define AnimBombYellow L"anim\\BombYellow.anim"
#define AnimBombExplosion L"anim\\BombExplosion.anim"

#define AnimSnakeIdle L"anim\\SnakeIdle.anim"
#define AnimSnakeWalk L"anim\\SnakeWalk.anim"
#define AnimSnakeAttack L"anim\\SnakeAttack.anim"
#define AnimRock L"anim\\Rock.anim"

#define AnimHUDHeart L"anim\\HUDHeart.anim"
#define AnimHUDBomb L"anim\\HUDBomb.anim"
#define AnimHUDRope L"anim\\HUDRope.anim"
#define AnimHUDScore L"anim\\HUDScore.anim"
#define AnimHUDTime L"anim\\HUDTime.anim"
#define AnimHUDStage L"anim\\HUDStage.anim"
#define AnimButtonIcon L"anim\\ButtonIcon.anim"

#define AnimPauseCursor L"anim\\PauseMenuCursor.anim"
#define AnimPauseMenuBoard L"anim\\PauseMenuBoard.anim"
#define AnimPauseHeader L"anim\\PauseHeader.anim"
#define AnimPauseRock L"anim\\PauseRock.anim"
#define AnimTitleAnyKey L"anim\\TitleAnyKey.anim"
#define AnimTitleBackground L"anim\\TitleBackground.anim"
#define AnimTitleGirl L"anim\\TitleGirl.anim"
#define AnimTitleCursor L"anim\\TitleCursor.anim"
#define AnimTitleSelect01 L"anim\\TitleSelect01.anim"
#define AnimTitleSelect02 L"anim\\TitleSelect02.anim"
#define AnimTitleSelect03 L"anim\\TitleSelect03.anim"
#define AnimTitleSelectDoor1 L"anim\\TitleSelectDoor1.anim"
#define AnimTitleSelectDoor2 L"anim\\TitleSelectDoor2.anim"
#define AnimTitleSelectFloor L"anim\\TitleSelectFloor.anim"

#define AnimTileUp1 L"anim\\TileUp1.anim"
#define AnimTileSideRight1 L"anim\\TileSide1.anim"
#define AnimTileBottom1 L"anim\\TileDown1.anim"

//////////////////////////////////////////////////////////
#define StatePlayerIdle L"CPlayerIdleState"
#define StatePlayerDown L"CPlayerDownState"
#define StatePlayerJumpUp L"CPlayerJumpUpState"
#define StatePlayerFallDown L"CPlayerFallDownState"
#define StatePlayerWalk L"CPlayerWalkState"
#define StatePlayerThrow L"CPlayerThrowState"
#define StatePlayerAttack L"CPlayerAttackState"
#define StatePlayerLadder L"CPlayerLadderState"

#define TexParticleRubbleAtlas L"texture\\atlas\\fx_rubble.png"
#define TexParticleSmallAtlas L"texture\\atlas\\fx_small.png"

#define StateEndSymbol "STATE_END"

//////////////////////////////////////////////////////

#define SndBGM_Title_Intro L"sound\\BGM_Title_Intro.ogg"
#define SndBGM_Title_Loop L"sound\\BGM_Title_Loop.ogg"

#define SndBGM_1_Adventure L"sound\\BGM_1_Adventure.ogg"
#define SndBGM_1_1HP_A L"sound\\BGM_1_1HP_A.ogg"
#define SndBGM_1_1HP_B L"sound\\BGM_1_1HP_B.ogg"
#define SndBGM_1_Add_A L"sound\\BGM_1_Add_A.ogg"
#define SndBGM_1_Add_B L"sound\\BGM_1_Add_B.ogg"
#define SndBGM_1_Brushu L"sound\\BGM_1_Brushu.ogg"
#define SndBGM_1_Chef L"sound\\BGM_1_Chef.ogg"
#define SndBGM_1_Delp_2 L"sound\\BGM_1_Delp_2.ogg"
#define SndBGM_1_Delp_4 L"sound\\BGM_1_Delp_4.ogg"
#define SndBGM_1_Gob_tran L"sound\\BGM_1_Gob_tran.ogg"
#define SndBGM_1_Goblet L"sound\\BGM_1_Goblet.ogg"
#define SndBGM_1_Idle L"sound\\BGM_1_Idle.ogg"
#define SndBGM_1_Leadup_A L"sound\\BGM_1_Leadup_A.ogg"
#define SndBGM_1_Leadup_B L"sound\\BGM_1_Leadup_B.ogg"
#define SndBGM_1_Meppa L"sound\\BGM_1_Meppa.ogg"
#define SndBGM_1_Ongaky L"sound\\BGM_1_Ongaky.ogg"
#define SndBGM_1_Ongrest L"sound\\BGM_1_Ongrest.ogg"
#define SndBGM_1_Sekatt L"sound\\BGM_1_Sekatt.ogg"
#define SndBGM_1_Shu_A L"sound\\BGM_1_Shu_A.ogg"
#define SndBGM_1_Shu_B L"sound\\BGM_1_Shu_B.ogg"
#define SndBGM_1_Shu_C L"sound\\BGM_1_Shu_C.ogg"
#define SndBGM_1_Yuzu L"sound\\BGM_1_Yuzu.ogg"
#define SndBGM_1_Yuzu_tem L"sound\\BGM_1_Yuzu_tem.ogg"


#define Sndtorch01 L"sound\\torch01.wav"
#define Sndtitle_select L"sound\\title_select.wav"
#define Sndspeartrap_02 L"sound\\speartrap_02.wav"
#define Sndmm_selection L"sound\\mm_selection.wav"
#define Sndwhip02a L"sound\\whip02a.wav"
#define Sndexplosion_d02 L"sound\\explosion_d02.wav"
