#pragma once

#define StatePlayerIdle L"CPlayerIdleState"
#define StatePlayerDown L"CPlayerDownState"
#define StatePlayerStart L"CPlayerStartState"
#define StateSnakeEntry L"CSnakeEntryState"
#define StateSnakeIdle L"CSnakeIdleState"
#define StateSnakeAttack L"CSnakeAttackState"
#define StatePlayerJumpUp L"CPlayerJumpUpState"
#define StatePlayerFallDown L"CPlayerFallDownState"
#define StatePlayerWalkLeft L"CPlayerWalkLeftState"
#define StatePlayerThrow L"CPlayerThrowState"
#define StatePlayerAttack L"CPlayerAttackState"
#define StatePlayerLadder L"CPlayerLadderState"
#define StatePlayerWalkRight L"CPlayerWalkRightState"
